namespace Somfic.Logging.Console.Builder
{
    public enum AnsiCode
    {
        Reset = 0,
        Bold = 1,
        Faint = 2, 
        Italic = 3,
        Underline = 4,
        SlowBlink = 5,
        RapidBlink = 6,
        Reverse = 7,
        Conceal = 8,
        CrossedOut = 9,
        PrimairyFont = 10,
        AlternativeFont1 = 11,
        AlternativeFont2 = 12,
        AlternativeFont3 = 13,
        AlternativeFont4 = 14,
        AlternativeFont5 = 15,
        AlternativeFont6 = 16,
        AlternativeFont7 = 17,
        AlternativeFont8 = 18,
        AlternativeFont9 = 19,
        Fraktur = 20,
        DoubleUnderline = 21,
        BoldReset = 21,
        ColorReset = 22,
        ItalicReset = 23,
        UnderlineReset = 24,
        BlinkReset = 25,
        ProportionalSpacing = 26,
        ReverseReset = 27,
        ConcealReset = 28,
        CrossedOutReset = 29,
        ForegroundBlack = 30,
        ForegroundRed = 31,
        ForegroundGreen = 32,
        ForegroundYellow = 33,
        ForegroundBlue = 34,
        ForegroundMagenta = 35,
        ForegroundCyan = 36,
        ForegroundWhite = 37,
        //ForegroundCustom = 38,
        ForegroundReset = 39,
        BackgroundBlack = 40,
        BackgroundRed = 41,
        BackgroundGreen = 42,
        BackgroundYellow = 43,
        BackgroundBlue = 44,
        BackgroundMagenta = 45,
        BackgroundCyan = 46,
        BackgroundWhite = 47,
        //BackgroundCustom = 48,
        BackgroundReset = 49,
        ProportionalSpacingReset = 50,
        Framed = 51,
        Encircled = 52,
        Overlined = 53,
        FramedReset = 54,
        EncircledReset = 54,
        OverlinedReset = 55,
        //UnderlineColorCustom = 58,
        UnderlineColorReset = 59,
        
        Superscript = 73,
        Subscript = 74,

        ForegroundGray = 90,
        ForegroundBrightRed = 91,
        ForegroundBrightGreen = 92,
        ForegroundBrightYellow = 93,
        ForegroundBrightBlue = 94,
        ForegroundBrightMagenta = 95,
        ForegroundBrightCyan = 96,
        ForegroundBrightWhite = 97,
       
        BackgroundGray = 100,
        BackgroundBrightRed = 101,
        BackgroundBrightGreen = 102,
        BackgroundBrightYellow = 103,
        BackgroundBrightBlue = 104,
        BackgroundBrightMagenta = 105,
        BackgroundBrightCyan = 106,
        BackgroundBrightWhite = 107
    }
}